### ISSUE TITLE
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y, : polygon edge not found

### ISSUE THREAD

**Issue by lloydhamilton** [sarinasinghkhaira/tidy_tuesday#1]
Hey Sarina!

I just clonned your repo and tragically I am unable to plot the nice graph you made. I got this error

`Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found`

after running code chunk starting at line 88. The error stop execution at line 138 at:

`ggsave(here("2021-04-06/deforestation_plot.png"), defo_plot, height = 8, width = 10)`

It's 10pm, I am starting to see double so will try and fix it tomorrow. As you can probably imagine after a day of coding at CodeClan!

Could I check with you what are the versions of the following packages you have installed? 

`library(tidyverse)`
`library(lubridate)`
`library(tidytext)`
`library(ggstream)`
`library(ggpomological)`

Regards,
Lloyd

**Comment by sarinasinghkhaira** [comment]
Hi Lloyd, 

Thanks so much for getting in touch and for flagging this up. That sort of error is due to the font not being installed on your computer/R.  I will add a note at the top of the script about this! 

A quick fix on your end is to change the font families on line 57 and 58 to Arial, or another font available on R. Fonts can be tricky on R, I use the package {extrafont} to help with them. If you run `extrafont::fonts()` you will see all of the fonts already loaded into R that you can use. 

If you'd like to use the fonts I used (Capriola and Nunito Sans) they are both freely available on Google fonts. After downloading them and adding them to your Font book on your mac, you can then run `extrafont::font_import()` so that you can use them in your plots. 

Hope that helps, let me know if you run into any other barriers. Hope you're enjoying the course!

**Comment by sarinasinghkhaira** [comment]
I should also note - there are multiple ways to load fonts into R. Another popular package is {sysfonts} but I can't get it to work on my mac!

**Comment by lloydhamilton** [comment]
That worked a dream! Thanks! I do prefer your fonts though...so I think I will download them. Love your work. I might jump on the tidy_tuesday band wagon.
